#!/bin/bash

# set your default secret key
defaultKey="~/.ssh/id_rsa"

# set your special secret key
## ["repository_account_name"]="your_secret_key"
## ex) ["mildjester"]="~/.ssh/mySpecialKey"
specialKeys=(
    'hogehoge::~/.ssh/fuga_key'
)
